### PR TITLE
Removes some deadlocks from the async code

### PR DESCRIPTION
**Pull request by emorell96**
This PR aims at removing any deadlock and adding the right tests to check for deadlocks for as many async methods as I can.

This is not ready to be merged yet. I have only done the dictionary async methods.

### CODE REVIEW

**Comment by emorell96** [comment]
This PR is ready for review, and merging.

It does two things:

1. Makes sure that all the awaits use .ConfigureAwait(false) and adds some tests testing for deadlocks in the collections and cache async methods.

2. Replaces the old MsgPack.Cli nuget in the MsgPackSerializer with https://github.com/neuecc/MessagePack-CSharp#readme which is faster and more active. Now this speed comes with a few disadvantages. Mainly the objects need to be annotated with attributes to allow serialization. The user needs to make sure that the objects have [MessagePackObject] on top of the class, and each property marked with a [Key(x)] attribute. You can read more here: https://github.com/neuecc/MessagePack-CSharp#readme

This last one means this might be a breaking version for people using this serializer since their code will break if they do not annotate their classes. This should probably be mentioned in the readme. 

I added a constructor to the MsgPackSerializer(MessagePackSerializerOptions options = null) so that the user can customize the behavior of the serializer.

Also users need to be aware that the DateTime loses the `Kind` information if serialized unless using the `NativeDateTimeResolver`: https://github.com/neuecc/MessagePack-CSharp#messagepackwriter

By the default the library uses ``MessagePackSerializerOptions.Standard.WithSecurity(MessagePackSecurity.UntrustedData)`` as suggested in their readme for security reasons.

This pretty much sums up this PR.

**Comment by emorell96** [comment]
Before publishing a new nuget, I think it would be a good idea to wait a little. I would like to add CancellationToken support to a lot of the async methods before a new version is released.

**Comment by thepirat000** [comment]
Why not to use the extension ForAwait from https://github.dev/StockDrops/CachingFramework.Redis/blob/master/src/CachingFramework.Redis/TaskExtensions.cs#L19 ?

**Comment by emorell96** [comment]
Also I was reading about cancellation tokens with StackExchange.Redis, and I incorrectly assumed they would have had added this by now: https://github.com/StackExchange/StackExchange.Redis/issues/1039 but they haven't. There's no CancellationToken support in StackExchange.Redis, so it makes no sense to add it here. So I guess my contributions are done, unless you have another thing you'd like to see in the library.

**Comment by emorell96** [comment]
They are passing on my machine before the merge on net 6.0
image

Any specific platform is failing?

**Comment by emorell96** [comment]
The only one failing for me on net461 is this:
image

Is it the same one failing for you?

**Comment by thepirat000** [comment]
yes, I think that's the only one failing

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by emorell96** [comment]
Ok, give me a sec. I am merging the master branch into my repo and I'll take a look.

**Comment by emorell96** [comment]
I am running the tests again, I think I know what's going on. The NoDeadlocks tests should just be about testing for no deadlocks, I left the other tests untouched which actually test correctness.

**Comment by thepirat000** [comment]
Are you going to fix the unit tests or should we remove them?

**Comment by emorell96** [comment]
Yes let me push

**Comment by emorell96** [comment]
image done

**Pull request merged**
